import { Track } from '@/lib/types'

export const intelTrack: Track = {
  id: 'intel',
  title: 'Intel & AMD CPU Architecture',
  shortTitle: 'Intel/AMD',
  description: 'Deep dive into CPU design, performance engineering, and CPU-specific optimization for ML inference. Covers x86 architecture, Xeon Scalable, AMD EPYC, and production inference engines.',
  moduleCount: 27,
  appendixCount: 5,
  icon: 'Microchip',
  color: 'cyan',
  parts: [
    {
      id: 'part-01-foundations',
      number: 1,
      title: 'Computer Systems Foundations',
      shortTitle: 'Systems Foundations',
      description: 'The CS:APP + OS layer — execution model, memory hierarchy, consistency, OS internals',
      modules: [
        { id: 'module-01', number: 1, title: 'The Execution Model Every Programmer Must Internalize', shortTitle: 'Execution Model', description: 'Process abstraction, virtual memory, context switching, system calls', readingTime: '30 min', sourceFile: 'module-01.md', href: '/intel/part-01-foundations/module-01' },
        { id: 'module-02', number: 2, title: 'Memory Hierarchy: The Single Most Important Topic', shortTitle: 'Memory Hierarchy', description: 'Cache organization, replacement policies, prefetching, NUMA topology', readingTime: '35 min', sourceFile: 'module-02.md', href: '/intel/part-01-foundations/module-02' },
        { id: 'module-03', number: 3, title: 'The Memory Consistency Model & Synchronization', shortTitle: 'Memory Consistency', description: 'TSO, sequential consistency, atomic operations, lock-free programming', readingTime: '30 min', sourceFile: 'module-03.md', href: '/intel/part-01-foundations/module-03' },
        { id: 'module-04', number: 4, title: 'Operating System Internals for Performance Engineers', shortTitle: 'OS Internals', description: 'Scheduling, interrupts, page tables, huge pages, cgroups', readingTime: '30 min', sourceFile: 'module-04.md', href: '/intel/part-01-foundations/module-04' },
      ],
    },
    {
      id: 'part-02-architecture',
      number: 2,
      title: 'Computer Architecture Deep Dive',
      shortTitle: 'Architecture',
      description: 'The Hennessy-Patterson + Mutlu layer — pipelining, OOO execution, branch prediction, SIMD',
      modules: [
        { id: 'module-05', number: 5, title: 'Pipelining & Hazards: The Foundation', shortTitle: 'Pipelining', description: 'Pipeline stages, data/control hazards, forwarding, stalls', readingTime: '30 min', sourceFile: 'module-05.md', href: '/intel/part-02-architecture/module-05' },
        { id: 'module-06', number: 6, title: 'Out-of-Order Execution: The Heart of Modern CPUs', shortTitle: 'OOO Execution', description: 'Tomasulo algorithm, ROB, reservation stations, register renaming', readingTime: '35 min', sourceFile: 'module-06.md', href: '/intel/part-02-architecture/module-06' },
        { id: 'module-07', number: 7, title: 'Branch Prediction: Modern State of the Art', shortTitle: 'Branch Prediction', description: 'Two-level predictors, TAGE, BTB, speculative execution', readingTime: '25 min', sourceFile: 'module-07.md', href: '/intel/part-02-architecture/module-07' },
        { id: 'module-08', number: 8, title: 'Instruction-Level Parallelism & Superscalar Execution', shortTitle: 'ILP & Superscalar', description: 'ILP limits, superscalar width, instruction windows, dispatch', readingTime: '30 min', sourceFile: 'module-08.md', href: '/intel/part-02-architecture/module-08' },
        { id: 'module-09', number: 9, title: 'SIMD & Vector Computing: AVX-512 Mastery', shortTitle: 'SIMD & AVX-512', description: 'SSE through AVX-512, vector intrinsics, auto-vectorization', readingTime: '35 min', sourceFile: 'module-09.md', href: '/intel/part-02-architecture/module-09' },
        { id: 'module-10', number: 10, title: 'Caches in Microarchitectural Detail', shortTitle: 'Cache Microarch', description: 'Set-associative caches, MSHR, non-blocking caches, prefetch streams', readingTime: '30 min', sourceFile: 'module-10.md', href: '/intel/part-02-architecture/module-10' },
        { id: 'module-11', number: 11, title: 'Memory Subsystem: DRAM to DIMM to Controller', shortTitle: 'Memory Subsystem', description: 'DRAM timing, rank/bank parallelism, memory controller scheduling', readingTime: '30 min', sourceFile: 'module-11.md', href: '/intel/part-02-architecture/module-11' },
      ],
    },
    {
      id: 'part-03-parallelism',
      number: 3,
      title: 'Parallelism & Concurrency Architecture',
      shortTitle: 'Parallelism',
      description: 'Multi-core design, thread-level parallelism, coherence protocols, interconnects',
      modules: [
        { id: 'module-12', number: 12, title: 'Multi-Core & Thread-Level Parallelism', shortTitle: 'Multi-Core & TLP', description: 'SMT, CMP, Amdahl\'s law, thread scheduling, affinity', readingTime: '30 min', sourceFile: 'module-12.md', href: '/intel/part-03-parallelism/module-12' },
        { id: 'module-13', number: 13, title: 'Coherence, Consistency, and Interconnects', shortTitle: 'Coherence & Interconnects', description: 'MESI/MOESI, snooping, directory protocols, mesh/ring interconnects', readingTime: '30 min', sourceFile: 'module-13.md', href: '/intel/part-03-parallelism/module-13' },
      ],
    },
    {
      id: 'part-04-performance',
      number: 4,
      title: 'Performance Engineering Methodology',
      shortTitle: 'Performance Engineering',
      description: 'Systematic performance analysis, profiling tools, compiler optimization',
      modules: [
        { id: 'module-14', number: 14, title: 'The Performance Engineering Framework', shortTitle: 'Perf Framework', description: 'Top-down analysis, bottleneck identification, roofline methodology', readingTime: '25 min', sourceFile: 'module-14.md', href: '/intel/part-04-performance/module-14' },
        { id: 'module-15', number: 15, title: 'Profiling Tools Mastery', shortTitle: 'Profiling Tools', description: 'perf, VTune, uProf, hardware performance counters', readingTime: '30 min', sourceFile: 'module-15.md', href: '/intel/part-04-performance/module-15' },
        { id: 'module-16', number: 16, title: 'Compiler Optimization & Code Generation', shortTitle: 'Compiler Optimization', description: 'ICC/GCC/LLVM optimization passes, PGO, LTO, vectorization reports', readingTime: '30 min', sourceFile: 'module-16.md', href: '/intel/part-04-performance/module-16' },
      ],
    },
    {
      id: 'part-05-xeon',
      number: 5,
      title: 'Intel Xeon Scalable: Complete Deep Dive',
      shortTitle: 'Intel Xeon',
      description: 'Microarchitecture evolution, Sapphire Rapids deep dive, memory subsystem, optimization',
      modules: [
        { id: 'module-17', number: 17, title: 'Intel Xeon Microarchitecture Evolution', shortTitle: 'Xeon Evolution', description: 'Skylake through Emerald Rapids progression, core and uncore changes', readingTime: '30 min', sourceFile: 'module-17.md', href: '/intel/part-05-xeon/module-17' },
        { id: 'module-18', number: 18, title: 'Sapphire Rapids (SPR) Microarchitecture In Depth', shortTitle: 'Sapphire Rapids', description: 'AMX, DSA, IAA, tile architecture, new instructions', readingTime: '35 min', sourceFile: 'module-18.md', href: '/intel/part-05-xeon/module-18' },
        { id: 'module-19', number: 19, title: 'Intel Xeon Memory Subsystem', shortTitle: 'Xeon Memory', description: 'DDR5, CXL, HBM integration, sub-NUMA clustering', readingTime: '30 min', sourceFile: 'module-19.md', href: '/intel/part-05-xeon/module-19' },
        { id: 'module-20', number: 20, title: 'Intel-Specific Performance Optimization Techniques', shortTitle: 'Intel Optimization', description: 'AMX programming, VNNI, DL Boost, kernel tuning for Xeon', readingTime: '30 min', sourceFile: 'module-20.md', href: '/intel/part-05-xeon/module-20' },
      ],
    },
    {
      id: 'part-06-epyc',
      number: 6,
      title: 'AMD EPYC: Complete Deep Dive',
      shortTitle: 'AMD EPYC',
      description: 'Zen microarchitecture evolution, Genoa deep dive, chiplet design, optimization',
      modules: [
        { id: 'module-21', number: 21, title: 'AMD Zen Microarchitecture Evolution', shortTitle: 'Zen Evolution', description: 'Zen 1 through Zen 4, chiplet design, infinity fabric', readingTime: '30 min', sourceFile: 'module-21.md', href: '/intel/part-06-epyc/module-21' },
        { id: 'module-22', number: 22, title: 'Zen 4 (Genoa) Microarchitecture In Depth', shortTitle: 'Zen 4 Genoa', description: 'CCD/IOD architecture, AVX-512, cache hierarchy changes', readingTime: '35 min', sourceFile: 'module-22.md', href: '/intel/part-06-epyc/module-22' },
        { id: 'module-23', number: 23, title: 'AMD EPYC Memory Subsystem', shortTitle: 'EPYC Memory', description: 'Infinity Fabric, NUMA topology, memory bandwidth optimization', readingTime: '30 min', sourceFile: 'module-23.md', href: '/intel/part-06-epyc/module-23' },
        { id: 'module-24', number: 24, title: 'AMD-Specific Optimization Techniques', shortTitle: 'AMD Optimization', description: 'NUMA-aware allocation, IF bandwidth tuning, AMD uProf', readingTime: '30 min', sourceFile: 'module-24.md', href: '/intel/part-06-epyc/module-24' },
      ],
    },
    {
      id: 'part-07-ml-engines',
      number: 7,
      title: 'Systems Design for ML Inference Engines',
      shortTitle: 'ML Inference Engines',
      description: 'CPU inference engine architecture, kernel implementation, end-to-end optimization',
      modules: [
        { id: 'module-25', number: 25, title: 'CPU Inference Engine Architecture', shortTitle: 'Engine Architecture', description: 'Graph IR, operator scheduling, memory planning, thread pools', readingTime: '35 min', sourceFile: 'module-25.md', href: '/intel/part-07-ml-engines/module-25' },
        { id: 'module-26', number: 26, title: 'Kernel Implementation for CPU Inference', shortTitle: 'Kernel Implementation', description: 'GEMM micro-kernels, activation functions, fused operators', readingTime: '35 min', sourceFile: 'module-26.md', href: '/intel/part-07-ml-engines/module-26' },
        { id: 'module-27', number: 27, title: 'End-to-End Performance Optimization Workflow', shortTitle: 'E2E Optimization', description: 'Full optimization workflow, benchmarking, deployment checklist', readingTime: '30 min', sourceFile: 'module-27.md', href: '/intel/part-07-ml-engines/module-27' },
      ],
    },
  ],
}
