import { Track } from '@/lib/types'

export const mlsysTrack: Track = {
  id: 'mlsys',
  title: 'ML Systems Engineering',
  shortTitle: 'MLsys',
  description: 'Production inference systems engineering — from fundamentals to specialized hardware deployment. Covers quantization, transformers, distributed inference, CPU/GPU/Apple Silicon/Edge AI, fine-tuning, voice AI, and RAG infrastructure.',
  moduleCount: 39,
  appendixCount: 5,
  icon: 'Cpu',
  color: 'blue',
  parts: [
    {
      id: 'part-01-inference-fundamentals',
      number: 1,
      title: 'Inference Optimization Fundamentals',
      shortTitle: 'Inference Fundamentals',
      description: 'Hardware-agnostic principles that apply everywhere',
      modules: [
        {
          id: 'module-01',
          number: 1,
          title: 'The Inference Systems Mental Model',
          shortTitle: 'Inference Mental Model',
          description: 'Production LLM inference architecture, roofline model, prefill vs decode phases, memory wall analysis',
          readingTime: '25 min',
          sourceFile: 'part_01_inference_fundamentals/module_01_inference_systems_mental_model.md',
          href: '/mlsys/part-01-inference-fundamentals/module-01',
        },
        {
          id: 'module-02',
          number: 2,
          title: 'Quantization: Complete Systems Perspective',
          shortTitle: 'Quantization',
          description: 'INT8/INT4/FP8 quantization, calibration strategies, GPTQ, AWQ, and production deployment',
          readingTime: '30 min',
          sourceFile: 'part_01_inference_fundamentals/module_02_quantization.md',
          href: '/mlsys/part-01-inference-fundamentals/module-02',
        },
        {
          id: 'module-03',
          number: 3,
          title: 'Sparsity: Structured & Unstructured',
          shortTitle: 'Sparsity',
          description: 'Pruning methods, structured sparsity, N:M patterns, sparse kernels, and hardware support',
          readingTime: '25 min',
          sourceFile: 'part_01_inference_fundamentals/module_03_sparsity.md',
          href: '/mlsys/part-01-inference-fundamentals/module-03',
        },
        {
          id: 'module-04',
          number: 4,
          title: 'Knowledge Distillation: Systems Perspective',
          shortTitle: 'Knowledge Distillation',
          description: 'Teacher-student architectures, distillation losses, production distillation pipelines',
          readingTime: '20 min',
          sourceFile: 'part_01_inference_fundamentals/module_04_knowledge_distillation.md',
          href: '/mlsys/part-01-inference-fundamentals/module-04',
        },
        {
          id: 'module-05',
          number: 5,
          title: 'Graph Optimization & Compilation',
          shortTitle: 'Graph Optimization',
          description: 'Operator fusion, graph rewriting, TVM, XLA, TensorRT compilation pipelines',
          readingTime: '25 min',
          sourceFile: 'part_01_inference_fundamentals/module_05_graph_optimization_compilation.md',
          href: '/mlsys/part-01-inference-fundamentals/module-05',
        },
      ],
    },
    {
      id: 'part-02-transformer-architecture',
      number: 2,
      title: 'Transformer Inference Architecture',
      shortTitle: 'Transformer Architecture',
      description: 'The algorithms that make LLM inference fast',
      modules: [
        {
          id: 'module-06',
          number: 6,
          title: 'Attention Mechanism: Systems Optimization',
          shortTitle: 'Attention Optimization',
          description: 'FlashAttention, multi-query/grouped-query attention, memory-efficient attention implementations',
          readingTime: '30 min',
          sourceFile: 'part_02_transformer_architecture/module_06_attention_optimization.md',
          href: '/mlsys/part-02-transformer-architecture/module-06',
        },
        {
          id: 'module-07',
          number: 7,
          title: 'KV-Cache Management Systems',
          shortTitle: 'KV-Cache Management',
          description: 'PagedAttention, vLLM memory management, KV-cache compression, continuous batching',
          readingTime: '25 min',
          sourceFile: 'part_02_transformer_architecture/module_07_kv_cache_management.md',
          href: '/mlsys/part-02-transformer-architecture/module-07',
        },
        {
          id: 'module-08',
          number: 8,
          title: 'Inference Serving Systems Architecture',
          shortTitle: 'Serving Systems',
          description: 'vLLM, TensorRT-LLM, request scheduling, continuous batching, SLA management',
          readingTime: '30 min',
          sourceFile: 'part_02_transformer_architecture/module_08_inference_serving_systems.md',
          href: '/mlsys/part-02-transformer-architecture/module-08',
        },
      ],
    },
    {
      id: 'part-03-distributed-inference',
      number: 3,
      title: 'Distributed Inference',
      shortTitle: 'Distributed Inference',
      description: 'Multi-device, multi-node inference at scale',
      modules: [
        {
          id: 'module-09',
          number: 9,
          title: 'Parallelism Strategies for Inference',
          shortTitle: 'Parallelism Strategies',
          description: 'Tensor parallelism, pipeline parallelism, expert parallelism for MoE models',
          readingTime: '25 min',
          sourceFile: 'part_03_distributed_inference/module_09_parallelism_strategies.md',
          href: '/mlsys/part-03-distributed-inference/module-09',
        },
        {
          id: 'module-10',
          number: 10,
          title: 'Communication Primitives & Collective Operations',
          shortTitle: 'Communication Primitives',
          description: 'AllReduce, AllGather, NCCL, bandwidth optimization, latency hiding',
          readingTime: '25 min',
          sourceFile: 'part_03_distributed_inference/module_10_communication_primitives.md',
          href: '/mlsys/part-03-distributed-inference/module-10',
        },
      ],
    },
    {
      id: 'part-04-cpu-inference',
      number: 4,
      title: 'Server-Grade CPU Inference',
      shortTitle: 'CPU Inference',
      description: 'Intel Xeon & AMD EPYC inference optimization',
      modules: [
        {
          id: 'module-11',
          number: 11,
          title: 'Why CPU Inference Matters & When It Wins',
          shortTitle: 'Why CPU Inference',
          description: 'Cost analysis, latency profiles, use cases where CPU beats GPU',
          readingTime: '20 min',
          sourceFile: 'part_04_cpu_inference/module_11_why_cpu_inference.md',
          href: '/mlsys/part-04-cpu-inference/module-11',
        },
        {
          id: 'module-12',
          number: 12,
          title: 'CPU Inference Engine Internals',
          shortTitle: 'CPU Engine Internals',
          description: 'OpenVINO, ONNX Runtime, llama.cpp architecture and kernel design',
          readingTime: '30 min',
          sourceFile: 'part_04_cpu_inference/module_12_cpu_inference_engines.md',
          href: '/mlsys/part-04-cpu-inference/module-12',
        },
        {
          id: 'module-13',
          number: 13,
          title: 'GEMM Optimization for CPU Inference',
          shortTitle: 'CPU GEMM Optimization',
          description: 'SIMD intrinsics, cache tiling, AMX/VNNI, micro-kernel design',
          readingTime: '30 min',
          sourceFile: 'part_04_cpu_inference/module_13_gemm_optimization_cpu.md',
          href: '/mlsys/part-04-cpu-inference/module-13',
        },
        {
          id: 'module-14',
          number: 14,
          title: 'Attention Implementation for CPU',
          shortTitle: 'CPU Attention',
          description: 'CPU-optimized attention kernels, SIMD attention, memory access patterns',
          readingTime: '25 min',
          sourceFile: 'part_04_cpu_inference/module_14_attention_cpu.md',
          href: '/mlsys/part-04-cpu-inference/module-14',
        },
        {
          id: 'module-15',
          number: 15,
          title: 'Full LLM Inference Pipeline on CPU',
          shortTitle: 'Full CPU Pipeline',
          description: 'End-to-end CPU inference, NUMA optimization, thread scheduling, production deployment',
          readingTime: '30 min',
          sourceFile: 'part_04_cpu_inference/module_15_full_pipeline_cpu.md',
          href: '/mlsys/part-04-cpu-inference/module-15',
        },
      ],
    },
    {
      id: 'part-05-apple-silicon',
      number: 5,
      title: 'Apple Silicon Inference',
      shortTitle: 'Apple Silicon',
      description: 'M-series unified memory architecture',
      modules: [
        {
          id: 'module-16',
          number: 16,
          title: 'Apple Silicon Architecture for ML Engineers',
          shortTitle: 'Apple Silicon Architecture',
          description: 'M-series SoC, unified memory, ANE, GPU architecture overview',
          readingTime: '25 min',
          sourceFile: 'part_05_apple_silicon/module_16_apple_silicon_architecture.md',
          href: '/mlsys/part-05-apple-silicon/module-16',
        },
        {
          id: 'module-17',
          number: 17,
          title: 'CoreML & ANE Programming',
          shortTitle: 'CoreML & ANE',
          description: 'CoreML optimization, ANE constraints, model conversion pipelines',
          readingTime: '25 min',
          sourceFile: 'part_05_apple_silicon/module_17_coreml_ane.md',
          href: '/mlsys/part-05-apple-silicon/module-17',
        },
        {
          id: 'module-18',
          number: 18,
          title: 'Metal & GPU Inference on Apple Silicon',
          shortTitle: 'Metal GPU Inference',
          description: 'Metal compute shaders, GPU inference kernels, performance tuning',
          readingTime: '25 min',
          sourceFile: 'part_05_apple_silicon/module_18_metal_gpu_inference.md',
          href: '/mlsys/part-05-apple-silicon/module-18',
        },
        {
          id: 'module-19',
          number: 19,
          title: 'llama.cpp on Apple Silicon',
          shortTitle: 'llama.cpp Apple',
          description: 'llama.cpp Metal backend, quantization on Apple Silicon, performance analysis',
          readingTime: '25 min',
          sourceFile: 'part_05_apple_silicon/module_19_llamacpp_apple.md',
          href: '/mlsys/part-05-apple-silicon/module-19',
        },
        {
          id: 'module-20',
          number: 20,
          title: 'Full Stack Inference on Apple Silicon',
          shortTitle: 'Full Stack Apple',
          description: 'Production deployment on Mac, ANE+GPU hybrid, memory management',
          readingTime: '25 min',
          sourceFile: 'part_05_apple_silicon/module_20_full_stack_apple.md',
          href: '/mlsys/part-05-apple-silicon/module-20',
        },
      ],
    },
    {
      id: 'part-06-edge-ai',
      number: 6,
      title: 'On-Device & Edge AI Inference',
      shortTitle: 'Edge AI',
      description: 'Mobile, embedded, microcontroller inference',
      modules: [
        {
          id: 'module-21',
          number: 21,
          title: 'Edge AI Hardware Landscape',
          shortTitle: 'Edge Hardware',
          description: 'Mobile SoCs, NPUs, microcontrollers, hardware comparison matrix',
          readingTime: '25 min',
          sourceFile: 'part_06_edge_ai/module_21_edge_hardware_landscape.md',
          href: '/mlsys/part-06-edge-ai/module-21',
        },
        {
          id: 'module-22',
          number: 22,
          title: 'TinyML: Inference on Microcontrollers',
          shortTitle: 'TinyML',
          description: 'TFLite Micro, memory-constrained inference, quantization for MCUs',
          readingTime: '20 min',
          sourceFile: 'part_06_edge_ai/module_22_tinyml.md',
          href: '/mlsys/part-06-edge-ai/module-22',
        },
        {
          id: 'module-23',
          number: 23,
          title: 'Mobile Inference: Android & iOS',
          shortTitle: 'Mobile Inference',
          description: 'TFLite, CoreML, NNAPI, mobile GPU delegates, on-device optimization',
          readingTime: '25 min',
          sourceFile: 'part_06_edge_ai/module_23_mobile_inference.md',
          href: '/mlsys/part-06-edge-ai/module-23',
        },
        {
          id: 'module-24',
          number: 24,
          title: 'Edge LLM Inference',
          shortTitle: 'Edge LLMs',
          description: 'Running LLMs on mobile/edge, model compression, speculative decoding on device',
          readingTime: '25 min',
          sourceFile: 'part_06_edge_ai/module_24_edge_llm.md',
          href: '/mlsys/part-06-edge-ai/module-24',
        },
      ],
    },
    {
      id: 'part-07-gpu-inference',
      number: 7,
      title: 'NVIDIA GPU Inference',
      shortTitle: 'GPU Inference',
      description: 'Modern GPU stack beyond Ampere',
      modules: [
        {
          id: 'module-25',
          number: 25,
          title: 'Modern GPU Inference Stack',
          shortTitle: 'GPU Stack',
          description: 'Hopper architecture, TensorRT-LLM, FlashAttention-3, FP8 inference',
          readingTime: '30 min',
          sourceFile: 'part_07_gpu_inference/module_25_modern_gpu_stack.md',
          href: '/mlsys/part-07-gpu-inference/module-25',
        },
      ],
    },
    {
      id: 'part-08-fine-tuning',
      number: 8,
      title: 'Fine-Tuning Systems',
      shortTitle: 'Fine-Tuning',
      description: 'Infrastructure for adapting trained models',
      modules: [
        {
          id: 'module-26',
          number: 26,
          title: 'Fine-Tuning Infrastructure',
          shortTitle: 'FT Infrastructure',
          description: 'Distributed fine-tuning, DeepSpeed, FSDP, checkpointing strategies',
          readingTime: '25 min',
          sourceFile: 'part_08_fine_tuning/module_26_finetuning_infrastructure.md',
          href: '/mlsys/part-08-fine-tuning/module-26',
        },
        {
          id: 'module-27',
          number: 27,
          title: 'LoRA & Parameter-Efficient Fine-Tuning',
          shortTitle: 'LoRA & PEFT',
          description: 'Low-rank adaptation, QLoRA, adapter methods, serving multi-LoRA',
          readingTime: '25 min',
          sourceFile: 'part_08_fine_tuning/module_27_lora_peft.md',
          href: '/mlsys/part-08-fine-tuning/module-27',
        },
        {
          id: 'module-28',
          number: 28,
          title: 'RLHF & Alignment Systems',
          shortTitle: 'RLHF & Alignment',
          description: 'PPO infrastructure, DPO, reward modeling, alignment training at scale',
          readingTime: '25 min',
          sourceFile: 'part_08_fine_tuning/module_28_rlhf_alignment.md',
          href: '/mlsys/part-08-fine-tuning/module-28',
        },
      ],
    },
    {
      id: 'part-09-voice-ai',
      number: 9,
      title: 'Fast Voice AI Systems',
      shortTitle: 'Voice AI',
      description: 'Streaming architecture, sub-100ms TTFA',
      modules: [
        {
          id: 'module-29',
          number: 29,
          title: 'Voice AI Pipeline Architecture',
          shortTitle: 'Voice Pipeline',
          description: 'End-to-end voice pipeline, latency budgets, streaming architecture',
          readingTime: '30 min',
          sourceFile: 'part_09_voice_ai/module_29_voice_pipeline_architecture.md',
          href: '/mlsys/part-09-voice-ai/module-29',
        },
        {
          id: 'module-30',
          number: 30,
          title: 'VAD (Voice Activity Detection) Systems',
          shortTitle: 'VAD Systems',
          description: 'Silero VAD, WebRTC VAD, streaming VAD architectures',
          readingTime: '20 min',
          sourceFile: 'part_09_voice_ai/module_30_vad.md',
          href: '/mlsys/part-09-voice-ai/module-30',
        },
        {
          id: 'module-31',
          number: 31,
          title: 'Streaming ASR',
          shortTitle: 'Streaming ASR',
          description: 'Whisper, CTC/RNN-T, streaming recognition, word-level timestamps',
          readingTime: '25 min',
          sourceFile: 'part_09_voice_ai/module_31_streaming_asr.md',
          href: '/mlsys/part-09-voice-ai/module-31',
        },
        {
          id: 'module-32',
          number: 32,
          title: 'LLM Integration in Voice Pipeline',
          shortTitle: 'LLM Voice Integration',
          description: 'Streaming LLM responses, turn-taking, interruption handling',
          readingTime: '25 min',
          sourceFile: 'part_09_voice_ai/module_32_llm_voice_integration.md',
          href: '/mlsys/part-09-voice-ai/module-32',
        },
        {
          id: 'module-33',
          number: 33,
          title: 'TTS (Text-to-Speech) Systems Engineering',
          shortTitle: 'TTS Systems',
          description: 'Neural TTS, streaming synthesis, voice cloning, latency optimization',
          readingTime: '25 min',
          sourceFile: 'part_09_voice_ai/module_33_tts.md',
          href: '/mlsys/part-09-voice-ai/module-33',
        },
        {
          id: 'module-34',
          number: 34,
          title: 'Audio Processing & Codec Systems',
          shortTitle: 'Audio Processing',
          description: 'Audio codecs, noise suppression, echo cancellation, audio pipeline',
          readingTime: '20 min',
          sourceFile: 'part_09_voice_ai/module_34_audio_processing.md',
          href: '/mlsys/part-09-voice-ai/module-34',
        },
        {
          id: 'module-35',
          number: 35,
          title: 'End-to-End Voice AI Optimization',
          shortTitle: 'E2E Voice Optimization',
          description: 'Full pipeline optimization, latency reduction, production deployment',
          readingTime: '25 min',
          sourceFile: 'part_09_voice_ai/module_35_e2e_voice_optimization.md',
          href: '/mlsys/part-09-voice-ai/module-35',
        },
      ],
    },
    {
      id: 'part-10-rag-infrastructure',
      number: 10,
      title: 'RAG & AI Systems Infrastructure',
      shortTitle: 'RAG & Infrastructure',
      description: 'Retrieval-augmented generation and production toolchain',
      modules: [
        {
          id: 'module-36',
          number: 36,
          title: 'RAG Systems Architecture',
          shortTitle: 'RAG Architecture',
          description: 'Retrieval pipelines, vector databases, chunking strategies, hybrid search',
          readingTime: '30 min',
          sourceFile: 'part_10_rag_infrastructure/module_36_rag_systems.md',
          href: '/mlsys/part-10-rag-infrastructure/module-36',
        },
        {
          id: 'module-37',
          number: 37,
          title: 'Deployment Toolchain',
          shortTitle: 'Deployment Toolchain',
          description: 'Model serving frameworks, containerization, orchestration, A/B testing',
          readingTime: '25 min',
          sourceFile: 'part_10_rag_infrastructure/module_37_deployment_toolchain.md',
          href: '/mlsys/part-10-rag-infrastructure/module-37',
        },
        {
          id: 'module-38',
          number: 38,
          title: 'Multimodal Inference',
          shortTitle: 'Multimodal Inference',
          description: 'Vision-language models, audio-text, multimodal serving architecture',
          readingTime: '25 min',
          sourceFile: 'part_10_rag_infrastructure/module_38_multimodal.md',
          href: '/mlsys/part-10-rag-infrastructure/module-38',
        },
        {
          id: 'module-39',
          number: 39,
          title: 'Observability & Monitoring',
          shortTitle: 'Observability',
          description: 'ML inference monitoring, latency tracking, model quality metrics, alerting',
          readingTime: '20 min',
          sourceFile: 'part_10_rag_infrastructure/module_39_observability.md',
          href: '/mlsys/part-10-rag-infrastructure/module-39',
        },
      ],
    },
  ],
}
